// The house's task list. Edit this file to change tasks, then restart the server.
// instructions = steps, supplies = tools needed, location = where the tools are kept.
// Other = no fixed schedule (done when needed); it shows as done for 90 days.
module.exports = [
  {
    name: 'Take out the trash',
    frequency: 'Daily',
    points: 2,
    instructions: ['Tie the full bags', 'Take them to the bins outside', 'Replace the bags when needed'],
    supplies: ['Trash bags'],
    location: '',
  },
  {
    name: 'Do the dishes',
    frequency: 'Daily',
     points: 1,
    instructions: ['Load the dishwasher, or wash by hand', 'Empty the clean dishwasher', 'Wipe the sink'],
    supplies: ['Dishwasher tablets', 'Dish soap', 'Sponge'],
    location: '',
  },
  {
    name: 'Pick up loose litter',
    frequency: 'Daily',
    points: 1,
    instructions: ['Walk through the common areas and the yard', 'Put litter in the right bin'],
    supplies: ['Trash bag'],
    location: '',
  },
  {
    name: 'Wipe the tables',
    frequency: 'Daily',
    points: 1,
    instructions: ['Clear the tables', 'Wipe with a damp cloth', 'Rinse the cloth and hang it to dry'],
    supplies: ['Cloth', 'All-purpose cleaner'],
    location: '',
  },

  {
    name: 'Wet-wipe surfaces and floors',
    frequency: 'Weekly',
    points: 5,
    instructions: ['Vacuum first', 'Wipe surfaces with a damp cloth', 'Mop the floors'],
    supplies: ['Vacuum cleaner', 'Mop and bucket', 'Floor cleaner', 'Cloth'],
    location: '',
  },
  {
    name: 'Clean the terrace floor',
    frequency: 'Weekly',
    points: 5,
    instructions: ['Move the furniture aside', 'Sweep the floor', 'Mop or hose down dirty spots'],
    supplies: ['Broom', 'Mop or hose'],
    location: '',
  },
  {
    name: 'Clean the swimming pool',
    frequency: 'Weekly',
    points: 8,
    instructions: ['Skim leaves off the surface', 'Brush the walls', 'Empty the filter basket', 'Vacuum the bottom', 'Check the water level'],
    supplies: ['Pool net', 'Pool brush', 'Pool vacuum hose'],
    location: '',
  },
  {
    name: 'Check car fluids and clear out car trash',
    frequency: 'Weekly',
    points: 3,
    instructions: ['Check oil, coolant and washer fluid levels', 'Top up washer fluid if needed', 'Take out any trash from the car'],
    supplies: ['Washer fluid', 'Trash bag'],
    location: '',
  },

  {
    name: 'Clean the hot tub',
    frequency: 'Biweekly',
    points: 3,
    instructions: ['Check the water and add chemicals if needed'],
    supplies: ['Filter cleaner', 'Sponge', 'Water test strips'],
    location: '',
  },
  {
    name: 'Clear fallen leaves and fruit from the trees',
    frequency: 'Biweekly',
    points: 5,
    instructions: ['Rake leaves and fallen fruit'],
    supplies: ['Rake', 'Garden bags', 'Gloves'],
    location: 'Outside',
  },
  {
    name: 'Pressure-wash the terrace and pool area',
    frequency: 'Biweekly',
    points: 5,
    instructions: ['Sweep loose dirt away first', 'Pressure-wash, keeping the nozzle moving', 'Roll up the hose when done'],
    supplies: ['Pressure washer', 'Hose', 'Broom'],
    location: 'Outside wall',
  },
  {
    name: 'Change the cat litter',
    frequency: 'Biweekly',
    points: 3,
    instructions: ['Empty the old litter into a bag', 'Wash the box', 'Fill with fresh litter'],
    supplies: ['Cat litter', 'Trash bag', 'Gloves'],
    location: 'Downstairs maintenance closet',
  },

  {
    name: 'Clean the bathroom tiles',
    frequency: 'Monthly',
    points: 5,
    instructions: ['Spray the tiles with bathroom cleaner', 'Scrub the grout lines', 'Rinse and dry'],
    supplies: ['Gloves', 'Bathroom cleaner', 'Scrubbing brush', 'Cloth'],
    location: 'Bathroom closet',
  },
  {
    name: 'Clean the showers',
    frequency: 'Monthly',
    points: 5,
    instructions: ['Clean the drain', 'Scrub the shower floor and walls', 'Wipe the glass and fittings'],
    supplies: ['Gloves', 'Bathroom cleaner', 'Scrubbing brush', 'Squeegee'],
    location: 'Bathroom closet',
  },
  {
    name: 'Wipe door handles and light switches',
    frequency: 'Monthly',
    points: 3,
    instructions: ['Go through every room', 'Wipe handles and switches with a damp cloth'],
    supplies: ['Cloth', 'All-purpose cleaner'],
    location: '',
  },
  {
    name: 'Wipe the railings',
    frequency: 'Monthly',
    points: 2,
    instructions: ['Wipe the railings with a damp cloth', 'Dry them so they do not stain'],
    supplies: ['Cloth','All purpose cleaner'],
    location: '',
  },

  {
    name: 'Defrost the freezer',
    frequency: 'Other',
    points: 5,
    instructions: [
      'Move the food to a cool box or another freezer',
      'Switch the freezer off and leave the door open',
      'Put towels on the floor and a tray under it',
      'Wipe the inside dry, switch it on and put the food back',
    ],
    supplies: ['Cool box', 'Towels', 'Tray', 'Cloth'],
    location: '',
  },
]
